// <auto-generated />
using Jokenpo.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Jokenpo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201011011047_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Jokenpo.Models.Jogador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CaminhoFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SobreNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("movementos")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Jogadores");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CaminhoFoto = "imagens/pedra.png",
                            Nome = "Pedro",
                            SobreNome = "asd",
                            movementos = 0
                        },
                        new
                        {
                            id = 2,
                            CaminhoFoto = "imagens/pedra.png",
                            Nome = "Pedro",
                            SobreNome = "asd",
                            movementos = 0
                        },
                        new
                        {
                            id = 3,
                            CaminhoFoto = "imagens/papel.png",
                            Nome = "Pedro",
                            SobreNome = "asd",
                            movementos = 0
                        },
                        new
                        {
                            id = 4,
                            CaminhoFoto = "imagens/tesoura.png",
                            Nome = "Pedro",
                            SobreNome = "asd",
                            movementos = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
